# Generated by Django 5.2.4 on 2025-07-08 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('edicao', models.CharField(max_length=100)),
                ('estado_conservacao', models.CharField(choices=[('N', 'Novo'), ('U', 'Usado'), ('D', 'Danificado')], max_length=1)),
                ('quantidade', models.PositiveIntegerField()),
            ],
        ),
    ]
