# Generated by Django 5.2.4 on 2025-07-08 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtgmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carta',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='assets/cartas_imagens'),
        ),
    ]
