# Generated by Django 5.2.4 on 2025-07-08 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtgmanager', '0002_carta_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='carta',
            name='tipo',
            field=models.CharField(choices=[('Criatura', 'Criatura'), ('Terreno Básico', 'Terreno Básico'), ('Terreno Não Básico', 'Terreno Não Básico'), ('Instantânea', 'Instantânea'), ('Encantamento', 'Encantamento'), ('Feitiço', 'Feitiço'), ('Planeswalker', 'Planeswalker'), ('Outro', 'Outro')], default='Outro', max_length=30),
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('formato', models.CharField(default='Commander', max_length=50)),
                ('comandante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decks_comandante', to='mtgmanager.carta')),
            ],
        ),
        migrations.CreateModel(
            name='CartaNoDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('carta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mtgmanager.carta')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartas', to='mtgmanager.deck')),
            ],
        ),
    ]
