# Generated by Django 5.2.4 on 2025-07-10 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtgmanager', '0003_carta_tipo_deck_cartanodeck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carta',
            name='imagem',
        ),
        migrations.AddField(
            model_name='carta',
            name='imagem_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
